name: m3allah
description: com.masritech.m3allah
publish_to: 'none'
version: 2.10.5+11

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  get_storage:
  animate_icons:
  simple_animations:
  scrollable_positioned_list:
  flutter_bloc:
  json_annotation:
  flutter_staggered_grid_view:
  wakelock:
  get:
  firebase_storage:
  audioplayers:
  flutter_svg:
  workmanager:
  flutter_local_notifications:
  lottie: ^1.3.0
  share_plus: ^4.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  build_runner:
  json_serializable:
  flutter_lints:
  flutter_launcher_icons:
#flutter pub run flutter_launcher_icons:main

  flutter_native_splash:
#flutter pub run flutter_native_splash:create


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter_native_splash:
  background_image: "assets/icon/icon.png"
  fullscreen: true
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/surah/
    - assets/azkar/
    - assets/fonts/
    - assets/translation/ar/
    - assets/translation/en/
    - assets/translation/id/


  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/font1.ttf
          weight: 500
    - family: font2
      fonts:
        - asset: assets/fonts/font2.ttf
          weight: 500
    - family: font3
      fonts:
        - asset: assets/fonts/font3.ttf
          weight: 500
    - family: font4
      fonts:
        - asset: assets/fonts/font4.ttf
          weight: 500
    - family: font5
      fonts:
        - asset: assets/fonts/font5.ttf
          weight: 500
    - family: font6
      fonts:
        - asset: assets/fonts/font6.ttf
          weight: 500
    - family: font7
      fonts:
        - asset: assets/fonts/font7.ttf
          weight: 500
