name: m3allah
description: com.masritech.m3allah
publish_to: 'none'
version: 2.5.1+10

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.0.2
  animate_icons:
  simple_animations:
  scrollable_positioned_list:
  flutter_bloc:
  json_annotation:
  flutter_staggered_grid_view:
  wakelock:
  get: ^4.6.1
  firebase_storage:
  audioplayers:
  flutter_svg:
  #workmanager:
  flutter_local_notifications:


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  build_runner:
  json_serializable:
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/surah/
     - assets/azkar/
     - assets/fonts/
     - assets/translation/ar/
     - assets/translation/en/
     - assets/translation/id/


  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/font1.ttf
          weight: 500
    - family: font2
      fonts:
        - asset: assets/fonts/font2.ttf
          weight: 500
    - family: font3
      fonts:
        - asset: assets/fonts/font3.ttf
          weight: 500
    - family: font4
      fonts:
        - asset: assets/fonts/font4.ttf
          weight: 500
    - family: font5
      fonts:
        - asset: assets/fonts/font5.ttf
          weight: 500
    - family: font6
      fonts:
        - asset: assets/fonts/font6.ttf
          weight: 500

