name: m3allah
description: com.masritech.m3allah
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_storage:
  animate_icons:
  simple_animations:
  scrollable_positioned_list:
  flutter_bloc:
  json_annotation:
  flutter_staggered_grid_view:
  flutter_zoom_drawer:
  wakelock:
  get:
  firebase_storage:
  audioplayers:
  awesome_notifications: 
  workmanager: ^0.4.1
  rename: 2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  freezed_annotation:
  build_runner:
  json_serializable:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.1.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  background_image: "assets/icon/icon.png"
  fullscreen: true
  android: true
  ios: true
  web: true


flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/surah/
     - assets/azkar/
     - assets/fonts/
     - assets/translation/ar/
     - assets/translation/en/
     - assets/translation/id/


  fonts:
    - family: font1
      fonts:
        - asset: assets/fonts/font1.ttf
          weight: 500
    - family: font2
      fonts:
        - asset: assets/fonts/font2.ttf
          weight: 500
    - family: font3
      fonts:
        - asset: assets/fonts/font3.ttf
          weight: 500
    - family: font4
      fonts:
        - asset: assets/fonts/font4.ttf
          weight: 500
    - family: font5
      fonts:
        - asset: assets/fonts/font5.ttf
          weight: 500
    - family: font6
      fonts:
        - asset: assets/fonts/font6.ttf
          weight: 500